image: docker:latest
services: 
  - name: docker:20-dind
    command: ["--tls=false"]

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay
  DOCKER_TLS_CERTDIR: ""

stages:
  - build
  - deploy

build:
  stage: build
  before_script:
    - docker --version
    - cd frontend
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD"
  script:
    - docker build -t bc-31-frontend:latest .
    - docker tag bc-31-frontend:latest "$CI_REGISTRY_USER"/bc-31-frontend:latest
    - docker push "$CI_REGISTRY_USER/bc-31-frontend:latest"
  only:
    - Deployment


deploy:
  stage: deploy
  image: kroniak/ssh-client
  before_script:
    - mkdir -p ~/.ssh
    - echo -e "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - touch ~/.ssh/config
    - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config 
  script:
    - ssh ubuntu@$SERVER_IP "sudo docker stop frontend"
    - ssh ubuntu@$SERVER_IP "sudo docker rm frontend"
    - ssh ubuntu@$SERVER_IP "sudo docker rmi "$CI_REGISTRY_USER/bc-31-frontend:latest""
    - ssh ubuntu@$SERVER_IP "sudo docker pull "$CI_REGISTRY_USER/bc-31-frontend:latest""
    - ssh ubuntu@$SERVER_IP "sudo docker run -d -p 3000:3000 --name frontend "$CI_REGISTRY_USER/bc-31-frontend:latest""
  only:
    - Deployment
  environment:
    name: Development
    url: http://13.59.167.171:3000


build-backend:
  stage: build
  before_script:
    - docker --version
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD"
  script:
    - cd backend
    - cd labmanagementservice
    - docker build -t bc31-lab:latest .
    - docker tag bc31-lab:latest "$CI_REGISTRY_USER"/bc31-lab:latest
    - docker push "$CI_REGISTRY_USER/bc31-lab:latest"
    - cd ..
    - cd ordermanagementservice
    - docker build -t bc31-order:latest .
    - docker tag bc31-order:latest "$CI_REGISTRY_USER"/bc31-order:latest
    - docker push "$CI_REGISTRY_USER/bc31-order:latest"
    - cd ..
    - cd reportmanagementservice
    - docker build -t bc31-report:latest .
    - docker tag bc31-report:latest "$CI_REGISTRY_USER"/bc31-report:latest
    - docker push "$CI_REGISTRY_USER/bc31-report:latest"
    - cd ..
  only:
    - Deployment
  environment:
    name: Staging

deploy-backend:
  stage: deploy
  image: kroniak/ssh-client
  before_script:
    - mkdir -p ~/.ssh
    - echo -e "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - touch ~/.ssh/config
    - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config 
  script:
    - ssh ubuntu@$SERVER_IP "sudo docker-compose down"
    - ssh ubuntu@$SERVER_IP "sudo docker rmi "$CI_REGISTRY_USER/bc31-lab:latest""
    - ssh ubuntu@$SERVER_IP "sudo docker rmi "$CI_REGISTRY_USER/bc31-order:latest""
    - ssh ubuntu@$SERVER_IP "sudo docker rmi "$CI_REGISTRY_USER/bc31-report:latest""
    - ssh ubuntu@$SERVER_IP "sudo docker-compose up -d"
  environment:
    name: Production
    url: http://13.59.167.171:9090
